service: aws-node-express-dynamodb-api-project
frameworkVersion: '3'
region: eu-west-1

custom:
  newsTableName: 'newsletter-table-${sls:stage}'
  iotTableName: 'iot-table-${sls:stage}'


provider:
  name: aws
  runtime: nodejs18.x
  stage: dev
  memorySize: 256
  region: eu-west-1
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource:
            - Fn::GetAtt: [ NewslettersTable, Arn ]
  environment:
    USERS_TABLE: ${self:custom.newsTableName}

functions:
  api:
    handler: index.handler
    events:
      - httpApi: '*'
resources:
  Resources:
    NewslettersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: email
            AttributeType: S
        KeySchema:
          - AttributeName: email
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
        TableName: ${self:custom.newsTableName}
